Algoritmo "media"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 5/9/2022
Var
// Seção de Declarações das variáveis 
mediaFinalAluno : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
mediaFinalAluno <- 70

se(mediaFinalAluno >= 70) entao
     escreva("Aluno foi Aprovado")
senao
     escreva("Aluno foi reprovado")
fimse

Fimalgoritmo