Algoritmo "Função Seno"
// 
//  
// Descrição   : Calcula o seno de um ângulo.
// Autor(a)    : Allen Halsay
// Data atual  : 5/10/2022
Var
// Seção de Declarações das variáveis

ang, angrad: real;


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
pi<-3.14159665;
escreva("Qual o ângulo em radianos?")
leia(ang)

angrad <- (ang * pi)/180;
escreval("O seno é ", angrad);



Fimalgoritmo